Docs: contributing/javascript: add the run of `npm install`
I got the following error when I ran it as per the documentation.

```
$ npm run build-js

> usearch@2.14.0 build-js
> tsc -p javascript/tsconfig-esm.json && tsc -p javascript/tsconfig-cjs.json && cp javascript/dist-package-esm.json javascript/dist/esm/package.json && cp javascript/dist-package-cjs.json javascript/dist/cjs/package.json

error TS2688: Cannot find type definition file for 'node'.
  The file is in the program because:
    Entry point of type library 'node' specified in compilerOptions

Found 1 error.
```

Add `npm install` is missing.