Docs: Update JavaScript code example
1. Add `require('node:assert')`
Fix the following error:
```
ReferenceError: assert is not defined
```

2. Change metric to `l2sq`

Fix the following error:
```
AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

Float32Array(1) [
  -0.00017893314361572266
]

should loosely deep-equal

Float32Array(1) [
  0
]
```

Reference:. https://github.com/unum-cloud/usearch/blob/242be104de770c12ed1fc938215530b944000b42/javascript/usearch.test.js#L49-L61